  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Publication"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"


 

  [[main]]
  name = "CV"
  weight = 600
  identifier = "cv"
  url = "/cv/"

